# 开启 OLED 屏幕支持
CONFIG_ZMK_DISPLAY=y

# 允许副控（右手）接收并刷新来自主控的状态数据
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

# 确保蓝牙状态图标正常显示
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
